### ISSUE TITLE
Expired HTTPS cert on the demo site

### ISSUE THREAD

**Issue by jc-dgit** [RatherLogical/Uptimon#5]
Looks like the https cert on the demo has expired. :wink:

![Screen Shot 2021-07-16 at 11 20 28 pm](https://user-images.githubusercontent.com/82353280/125954787-3b587fd3-4eea-4082-a4bf-31364b01b2c0.png)

**Comment by RatherLogical** [comment]
It's been resolved, sorry for that. The cron job for acme.sh was not set up properly.
